### ISSUE TITLE
Thread vs Coroutines - Coroutines throw OutOfMemory

### ISSUE THREAD

**Issue by ghost** [renatomrcosta/bootiful-rsocket-vkug-demo#1]
Hi Renato,

I am using JUnit to run my tests and have following two tests in a spring boot application:

```kotlin
@Test
	fun withThreads() {
		val time = measureTimeMillis {
			List(100_000) {
				thread {
					Thread.sleep(1000)
					println("${Thread.currentThread().name} Executed Thread: $it")
				}
			}.forEach {
				it.join()
			}
		}
		println("Total Time taken: $time")
	}

	@Test
	fun withCoroutines() {
		val time = measureTimeMillis {
			runBlocking {
				List(100_000) {
					launch {
						delay(1000)
						println("${Thread.currentThread().name} Executed Job: $it")
					}
				}
			}
		}
		println("Total time taken: $time")
	}

```
On my system Ubuntu 18.4, the co-routine test fails and throw out of memory exception. However, the one which usages threads run successfully. I am not sure why that is the case, the co-routines should be more efficient. 

Thank you,

**Comment by renatomrcosta** [comment]
Hi Singh! Thanks for reaching out. Turns out, I can reproduce the error in this case, which right now doesn't make a lot of sense to me. I'm inclined to believe that JUnit is a poor match to run suspenseful code, it almost seems to me like the coroutines are stuck due to blocked threads! But let's go by parts:

Try creating just a simple Kotlin file (without using being a JUnit test, I mean), and running the blocks you coded above in a `fun main()` function. It should always work for the coroutines version, and never for the Thread version.

But to get the coroutine version working in the tests while still using JUnit, we can give a dispatcher with different thread(s) from the JUnit executor. This helps us assert that our code is fine, but something is blocking the execution of the coroutines in the JUnit thread in context:

```kotlin
// Works while running on a IO Dispatcher:
@Test
    fun coroutineTest() {
        runBlocking(Dispatchers.IO){
            List(100_000) {
                launch {
                    delay(1_000)
                    println("Job Complete!")
                }
            }
        }
    }

// Works while running in a single thread!
@Test
fun coroutineTest() {
        runBlocking(newSingleThreadContext("My Thread")){
            List(100_000) {
                launch {
                    delay(1_000)
                    println("Job Complete!")
                }
            }
        }
    }
```

So yeah... JUnit seems not to play terribly nice with a lot of coroutines on its threads. What could we do about that? I normally use Kotest (https://github.com/kotest/kotest). It a pretty elegant, flexible and coroutine friendly library. To do so, we add the dependencies to our `build.gradle`:
```kotlin
   testImplementation("io.kotest:kotest-runner-junit5-jvm:${kotest_version}")
    testImplementation("io.kotest:kotest-assertions-core-jvm:${kotest_version}")
    testImplementation("io.kotest:kotest-property-jvm:${kotest_version}")
```

and write our tests in our favorite spec (I am very partial to DescribeSpec):
```kotlin
class TestingCoroutinesTest : DescribeSpec() {
    init {
        describe("Testing coroutines!") {
            it("should work with 100K jobs") {
                List(100_000) {
                    launch {
                        delay(1_000)
                        println("Job Complete!")
                    }
                }
            }
        }
   }
}
```

Notice we don't even need to add a `runBlocking` block! The TestContext provided by KoTest is already in a coroutine scope, and works out of the box with them!

I hope this was helpful! TL;DR: JUnit is probably blocking the thread where your test has to run and messing up the coroutines execution. You can avoid using the Threads provided by JUnit altogether, but I'd recommend simply hopping to a test library that is coroutine specific, such as Kotest.

**Comment by ghost** [comment]
Thank you Renato!
